name = "app-links-manager"
pages_build_output_dir = "build/client"
compatibility_date = "2025-02-08"

[[d1_databases]]
database_id = "3b64f2eb-9377-4669-b85a-52a930937892"
binding = "DB"
database_name = "app-links-manager"
preview_database_id = "5c41e03f-0ba1-4c7d-ba77-87f07b38c15d"

[env.preview]
name = "app-links-manager-preview"
compatibility_date = "2025-02-08"

[[env.preview.d1_databases]]
database_id = "5c41e03f-0ba1-4c7d-ba77-87f07b38c15d"
binding = "DB"
database_name = "app-links-manager-preview"