services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    tty: true
    image: app-links-manager
    container_name: app-links-manager-container
    environment:
      TZ: 'Asia/Tokyo'
    network_mode: 'host'
