name: Delete Preview

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview deployment
        run: |
          response=$(curl -s -X DELETE "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ github.event.repository.name }}/deployments?branch=${{ github.event.pull_request.head.ref }}" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json")
          
          if ! echo "$response" | jq -e '.success' > /dev/null; then
            echo "Failed to delete preview deployment"
            echo "Error: $(echo "$response" | jq -r '.errors[0].message // "Unknown error"')"
            exit 1
          fi
          
          echo "Successfully deleted preview deployment"