name: Deploy Preview

on:
  push:
    branches:
      - 'feature/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get preview URL
        id: preview-url
        run: |
          PREVIEW_URL="https://preview.${GITHUB_REPOSITORY#*/}.pages.dev"
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

      - name: Deploy pages
        uses: ./.github/actions/deploy
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          branch-name: preview
